### ISSUE TITLE
Import error with S3

### ISSUE THREAD

**Issue by olawale1rty** [MadeByMads/fastapi-cloud-drives#29]
You cant access S3 using from `fastapi_cloud_drives import S3`

**Comment by AliyevH** [comment]
> You cant access S3 using from `fastapi_cloud_drives import S3`

What do you mean? Can you please give more information about issue?

**Comment by olawale1rty** [comment]
In the __init__.py file, S3 and S3Config are not passed to the array of __all__ variables which makes importing it gives error in your codes. The fix for it is simply adding it to the array.

```
from fastapi_cloud_drives.fastapi_google import GoogleDrive
from fastapi_cloud_drives.fastapi_dropbox import DropBox
from fastapi_cloud_drives.fastapi_s3 import S3

from fastapi_cloud_drives.config import GoogleDriveConfig
from fastapi_cloud_drives.config import DropBoxConfig
from fastapi_cloud_drives.config import S3Config

__author__ = "hasan.aliyev.555@gmail.com"

__all__ = [
    "S3", "S3Config", "GoogleDrive", "GoogleDriveConfig", "DropBoxConfig", "DropBox"
]
```
